diff --git a/Zend/tests/generators/yield_from_valid_exception.phpt b/Zend/tests/generators/yield_from_valid_exception.phpt
index 3af35f53af..d3e054bfaf 100644
--- a/Zend/tests/generators/yield_from_valid_exception.phpt
+++ b/Zend/tests/generators/yield_from_valid_exception.phpt
@@ -15,7 +15,8 @@ class FooBar implements Iterator {
 
 function gen() {
     try {
-        yield from new FooBar;
+        // the fact that the yield from result is used is relevant.
+        var_dump(yield from new FooBar);
     } catch (Exception $e) {
         echo $e->getMessage(), "\n";
     }
diff --git a/Zend/zend_generators.c b/Zend/zend_generators.c
index bb3260b11b..0ed92f4ca2 100644
--- a/Zend/zend_generators.c
+++ b/Zend/zend_generators.c
@@ -740,7 +740,7 @@ static int zend_generator_get_next_delegated_value(zend_generator *generator) /*
 	return SUCCESS;
 
 exception:
-	zend_rethrow_exception(generator->execute_data);
+	zend_generator_throw_exception(generator, NULL);
 
 failure:
 	zval_ptr_dtor(&generator->values);
